// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjl0tpf-7Rqjd8HR4QfDaDHlKkPk6f28w',
    appId: '1:127997637292:web:637303b82d49cb909b2509',
    messagingSenderId: '127997637292',
    projectId: 'belallllcourse4',
    authDomain: 'belallllcourse4.firebaseapp.com',
    storageBucket: 'belallllcourse4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvVCLT_zCqpCh9kDwZ-D8hh3XqrCRYMk',
    appId: '1:127997637292:android:5a5674e24ae0f2d99b2509',
    messagingSenderId: '127997637292',
    projectId: 'belallllcourse4',
    storageBucket: 'belallllcourse4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8TMtOgz5v2Ex68ramOXlNgcfFflediY',
    appId: '1:127997637292:ios:348e4d358f7dd22e9b2509',
    messagingSenderId: '127997637292',
    projectId: 'belallllcourse4',
    storageBucket: 'belallllcourse4.firebasestorage.app',
    iosClientId: '127997637292-gdgeo1doalfin25vbh4rk6i3a4i09pqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8TMtOgz5v2Ex68ramOXlNgcfFflediY',
    appId: '1:127997637292:ios:348e4d358f7dd22e9b2509',
    messagingSenderId: '127997637292',
    projectId: 'belallllcourse4',
    storageBucket: 'belallllcourse4.firebasestorage.app',
    iosClientId: '127997637292-gdgeo1doalfin25vbh4rk6i3a4i09pqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjl0tpf-7Rqjd8HR4QfDaDHlKkPk6f28w',
    appId: '1:127997637292:web:9ce4dd2b98a894e59b2509',
    messagingSenderId: '127997637292',
    projectId: 'belallllcourse4',
    authDomain: 'belallllcourse4.firebaseapp.com',
    storageBucket: 'belallllcourse4.firebasestorage.app',
  );

}